### PR TITLE
updated to add wrapper for daemonsets

### PR DESCRIPTION
**Pull request by gileshinchcliff**

### CODE REVIEW

**Comment by timgent** [comment]
Should we be doing this in bash or in golang?

**Comment by gileshinchcliff** [comment]
totally in golang, long term, this just pushes me over the edge for a piece of work I need to deliver.

**Comment by vaijab** [comment]
I appreciate the work, however I don't think that this script fits in this repo. You could include this script as a function in your deploy.sh or similar.

I looked into daemonsets and couldn't find a reliable way to check whether a daemonset has been successfully deployed. Also kubernetes people are working on proper deployments of daemonsets.

**Comment by jon-shanks** [comment]
This definitely needs to be in golang and we dont want to mix bash and golang and further complicate a tool. Couldn't you just delete the daemonset and create to get by until these features are in kubectl?

**Pull request closed without merging**
